#!/usr/bin/php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require_once(__DIR__ . '/../../autoload.php');
}

$paramSprintName = $_SERVER['argv'][1] ?? null;
if ($paramSprintName === null) {
    echo "Please enter a valid sprint name. \nExample:\n> aireleasenotes \"Spryker Sprint 20\"";
    exit(0);
}

$releaseNotes = new \AiJira\ReleaseNotes\ReleaseNotes();
echo $releaseNotes->getReleaseNotesFromMergeRequests($paramSprintName);
