#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require_once(__DIR__ . '/../../autoload.php');
}

$sprintName = $_SERVER['argv'][1] ?? null;
if ($sprintName === null) {
    echo "Please enter a valid sprint name. \nExample:\n> aisprintgoals \"Spryker Sprint\"";
    exit(0);
}

$overwritePrompt = $_SERVER['argv'][2] ?? null;

$sprintGoals = new \AiJira\SprintGoals\SprintGoals();
echo $sprintGoals->generateSprintGoals($sprintName, $overwritePrompt);
