#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require_once(__DIR__ . '/../../autoload.php');
}

$ticketNumber = $_SERVER['argv'][1] ?? null;
if ($ticketNumber === null) {
    echo "Please enter a valid ticket number. \nExample:\n> aiticketinterview \"SPRY-1234\"";
    exit(0);
}

$ticketInterview = new \AiJira\TicketInterview\TicketInterview();
echo $ticketInterview->getTicketInterviewQuestions($ticketNumber);
